### ISSUE TITLE
Problem with console.developers.google.com !!

### ISSUE THREAD

**Issue by hozviyat** [backtory/fod#102]
سلام
سایت
https://console.developers.google.com
رو نمیتونم بازکنم!!!
لطفا راهنماییم کنید.
ممنون

**Comment by behdad222** [comment]
@hozviyat سلام
این سرویس برای وب گردی ساخته نشده

**Comment by hozviyat** [comment]
نه برای وب گردی نمیگم.
وقتی از بخش ای پی آی، برای نقشه گوگل مپس، api بگیرم،
بهم نشونش نمیده.
حتی موقع ساخت پروژه جدید، به شکل عجیبی، دکمه create غیر فعاله.
خلاصه ممنون میشم راهنماییم کنید.

**Comment by behdad222** [comment]
@hozviyat شاید بد توضیح دادم
مناسب استفاده تو براوزر نیست
زمانی که یه وب‌سایت رو باز میکنید ممکن هست به دامین‌های مختلف که تو لیست fod نیستند ریکوست بزنه در نتیجه این ریکوست‌ها به مشکل میخورند
