### ISSUE TITLE
New domain

### ISSUE THREAD

**Issue by rezaiyan** [backtory/fod#104]
Please add the  [fabric](https://fabric.io) to the domains list.

**Comment by behdad222** [comment]
@rezaiyan آقا فبریک مدت‌هاست اضافه میشه و منم بازش میکنم
ولی انگار یه مشکلی هست که بعضی‌ها دارن
میشه بیشت رتوضیح بدی کجاش داستان داره؟

**Comment by rezaiyan** [comment]
وقتی دپندنسی شو اضافه میکنم، موقع دریافت از مخزن خطای 403 میده

_Sent from my Xiaomi MI 3W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by behdad222** [comment]
من باز تست کردم و کار کرد
اگر تونستی آدرسی که می‌خواد ازش دانلود کنه رو برام بفرست

**Comment by rezaiyan** [comment]
<p dir="rtl">
فکر میکنم مشکل از ISP من باشه
</p>
