### ISSUE TITLE
CDN servers...

### ISSUE THREAD

**Issue by EleRam** [backtory/fod#107]
سلام
متاسفانه تعدادی از سی.دی.ان ها از داخل فیلتر شدند و البته متوجه هدف شما هم هستم که برای تحریم شده ها می خواید این کار انجام بشه اما متاسفانه این فیلتر ها رو واقعا نمیشه کاری کرد و محتوی هم غالبا مشکلی نداره
نمونه: 
https://tympanus.net
که از  netdna-ssl.com استفاده کرده و سایت عملا برای ایرانی ها باز نمیشه...

اگه بشه که این جور موارد هم بیاد توی لیست خیلی خوب میشه.
متشکرم

**Comment by behdad222** [comment]
@EleRam بهتر هست درخواست رفع فیلتر بدید
http://rafefilter.internet.ir/index.html

**Comment by EleRam** [comment]
قبلا اینکار رو انجام ندادم و متاسفانه بعد این همه مدت هنوز وضع همینه
