### ISSUE TITLE
www.upwork.com

### ISSUE THREAD

**Issue by mphj** [backtory/fod#129]
Hi! please add this site to the proxy.
good site for freelancers!

**Comment by drhossein** [comment]
why u don't use this service? https://shecan.ir

it provided a dns proxy so u can use any blocked site with just a tiny dns configuration. give it a try.

**Comment by behdad222** [comment]
@drhossein It's not safe

**Comment by Azoic** [comment]
> why u don't use this service? https://shecan.ir
> 
> it provided a dns proxy so u can use any blocked site with just a tiny dns configuration. give it a try.

وقتی از دی ان اس استفاده میکنید کل ترافیک شما از مسیر سرور اونا عبور میکنه اما با پروکسی میتونید تنظیم کنید صرفا سایت های بخصوصی از این طریق باز بشن
