### ISSUE TITLE
چطور ممکنه؟!

### ISSUE THREAD

**Issue by mirismaili** [backtory/fod#132]
سلام
ممنون از خدمات خوبتون. سؤالی که برای من ایجاد شد اینه که اگر سرورهاتون داخل ایرانه، آی. پی. سرورهای خودتون هم باید تحریم باشه. پس چطور چنین چیزی ممکنه؟ آیا پای پراکسی دومی هم در میونه؟

**Comment by behdad222** [comment]
بله
یه سرور هم اونور هست
@mirismaili
