### ISSUE TITLE
add mail services

### ISSUE THREAD

**Issue by amircup2006** [backtory/fod#14]
Hi
Please add mailgun.com and sendgrid.com in your whitelists
Regards.

**Comment by amircup2006** [comment]
And also Please add http://google.com/analytics to this service.
tnx

**Comment by behdad222** [comment]
@oraclenik 
any idea for http://google.com/analytics ?

**Comment by amircup2006** [comment]
Why did you remove mailgun from the list?

**Comment by behdad222** [comment]
https://github.com/backtory/fod/pull/22/commits/27ff059ce9c037647c4d6674b627adfe47892d81
