### ISSUE TITLE
How to add your proxy in "SDK Update Sites" part?

### ISSUE THREAD

**Issue by Drjacky** [backtory/fod#17]
How to add your proxy in "SDK Update Sites" part?

Please give us the whole URL to your repository XML file.
It's something like:
`https://yourdomainname/android/repository/addon.xml`
Or
`https://yourdomainname/files/android/xml/repository-10.xml`

![image](https://user-images.githubusercontent.com/2296754/27507510-14cda6cc-58e6-11e7-803c-81f721010f4b.png)

**Comment by behdad222** [comment]
it's a proxy service
please read [](https://github.com/backtory/fod#android-studio)

**Comment by Drjacky** [comment]
Thanks. Unfortunately, I used that section for something else.
So if there is no way to communicate with that XML file, please close this issue.

**Comment by behdad222** [comment]
use proxyfire and set roles for each proxy
also you can use [cow](https://github.com/cyfdecyf/cow/blob/master/README-en.md)
