### ISSUE TITLE
Problem with Vuforia !!!

### ISSUE THREAD

**Issue by hozviyat** [backtory/fod#53]
سلام دوستان
من نمی تونم توی
https://developer.vuforia.com/
لاگین بشم.
لطفا راهنماییم کنید...

**Comment by behdad222** [comment]
@hozviyat سویچی شارپ رو کروم نصب کن
توضیحاتش تو readme هست
تنظیمات پراکسی روش ست کن
و بزن ترافیکت ازش بگزره
موقع لاگین رو آیکنش بزن و ببین failed resource ها چیاست
اونارو pull request بفرست
