### ISSUE TITLE
Request for add doc.datastax.com

### ISSUE THREAD

**Issue by mostafa-asg** [backtory/fod#54]
Datastax.com is main contributer of Apache Cassandra.This site has documentation , articles and resources about Cassandra.
Unfortunately we can't access to the documentation (http://docs.datastax.com)

**Comment by oraclenik** [comment]
Hi My friend,
Do you just need  "docs.datastax.com"  not any other subdomains?

**Comment by mostafa-asg** [comment]
Hi
It seems that other sub domains like "academy.datastax.com" is open right now.

**Comment by mostafa-asg** [comment]
Any progress?

**Comment by oraclenik** [comment]
Why don't you add it your self, just git push your changes in domains file
then we will check it out and merge it :)
