### ISSUE TITLE
Issue in using  *.fabric.io

### ISSUE THREAD

**Issue by beigirad** [backtory/fod#79]
Hello 
Your service has an issue when I use [CrashLytics](https://fabric.io) in my Project.
Error : 
Error:Could not GET 'https://maven.fabric.io/public/io/fabric/tools/gradle/maven-metadata.xml'. Received status code 403 from server: Forbidden

**Comment by Menooa** [comment]
same issue :(

**Comment by behdad222** [comment]
https://github.com/backtory/fod/blob/master/domains#L47
https://github.com/backtory/fod/blob/master/domains#L51

Probably another domain

**Comment by behdad222** [comment]
@Menooa @beigirad 
check this
https://github.com/backtory/fod#gradle

`systemProp.http.proxyHost=fod.backtory.com
systemProp.http.proxyPort=8118
systemProp.https.proxyHost=fod.backtory.com
systemProp.https.proxyPort=8118`
