### ISSUE TITLE
Request to add slack

### ISSUE THREAD

**Issue by sllikson** [backtory/fod#91]
سلام.
سایت اسلک اخیرا ایران رو تحریم کرده. لطفا به لیست اضافه کنیدش.
ممنون
slack.com

**Comment by behdad222** [comment]
@sllikson اسلک قبلا اضافه شده

**Comment by amirakhavan** [comment]
سلام
برای تیم‌ویوور هم قابل استفاده است؟
چون فقط سایتش رو میشه باهاش باز کرد ولی با ست کردن پرکسی در خود نرم‌افزار کار نمیکنه
