### ISSUE TITLE
preview.themeforest.net doesn't work

### ISSUE THREAD

**Issue by l3est** [backtory/fod#92]
this domain is in domains file, but id doesn't work because it has iframe (which is not from themeforest domain) 
is there any way to load the iframe without proxy but use proxy for the main page?

here is the code of preview.themeforest.net page:
https://pasteboard.co/GTh02e3f.png

**Comment by behdad222** [comment]
@l3est 
you can use [SwitchyOmega](https://github.com/backtory/fod#chrome) or [foxyproxy](https://github.com/backtory/fod#فایرفاکس)

**Comment by l3est** [comment]
@behdad222 I'm already using switchy omega, but it doesn't work. maybe I'm using wrong settings.
themeforest.net works fine but preview.themeforest.net doesn't work. iframe is not from themeforest but I think it tries to use FOD proxy.

**Comment by behdad222** [comment]
@l3est use auto switch mode and define rules
for example
![screenshot from 2017-11-12 15-22-47](https://user-images.githubusercontent.com/3942191/32698608-7ce30978-c7bd-11e7-9689-7dc0221461fd.png)

**Comment by l3est** [comment]
Isn't this the same?
fod is proxy and "Default" is [Direct]
https://pasteboard.co/GTiBqzJ.png

**Comment by behdad222** [comment]
maybe
