### ISSUE TITLE
TeamViewer

### ISSUE THREAD

**Issue by amirakhavan** [backtory/fod#93]
سلام
برای تیم‌ویوور هم قابل استفاده است؟
چون فقط سایتش رو میشه باهاش باز کرد ولی با ست کردن پروکسی در خود نرم‌افزار کار نمیکنه

**Comment by behdad222** [comment]
@oraclenik من الان با پراکسی خودم یه تست کردم
تو پراکسی خودش زدم کار نکرد
پراکسی فایر زدم کار نکرد رو مک
ولی یادم هست یه بار رو ویندوز تونستم ترافیک رو ازش رد کنم
اگر اشتباه نکنم با کلاینت ویندوزی شدوساکس تونستم
